INSERT INTO public."Products"(nameproduct) VALUES ('Альбумін');
INSERT INTO public."Products"(nameproduct) VALUES ('Арахіс сирий очищений');
INSERT INTO public."Products"(nameproduct) VALUES ('Астрі крем');
INSERT INTO public."Products"(nameproduct) VALUES ('Астрі гель');
INSERT INTO public."Products"(nameproduct) VALUES ('Астрі Берлінер');
INSERT INTO public."Products"(nameproduct) VALUES ('Баз Темний');
INSERT INTO public."Products"(nameproduct) VALUES ('Барвник харчовий червоний');
INSERT INTO public."Products"(nameproduct) VALUES ('Барвник харчовий жовтий');
INSERT INTO public."Products"(nameproduct) VALUES ('Барвник харчовий зелений');
INSERT INTO public."Products"(nameproduct) VALUES ('Барвник харвчовий синій');
INSERT INTO public."Products"(nameproduct) VALUES ('Борошно житнє обдирне');
INSERT INTO public."Products"(nameproduct) VALUES ('Борошно пшеничне В/Г');
INSERT INTO public."Products"(nameproduct) VALUES ('Ванілін порошкоподібний');
INSERT INTO public."Products"(nameproduct) VALUES ('Вишні свіжозаморожені');
INSERT INTO public."Products"(nameproduct) VALUES ('Вершки');
INSERT INTO public."Products"(nameproduct) VALUES ('Горох');
INSERT INTO public."Products"(nameproduct) VALUES ('Гофроящик 700/240/230');
INSERT INTO public."Products"(nameproduct) VALUES ('Гофроящик 800*250*300');
INSERT INTO public."Products"(nameproduct) VALUES ('Гофроящик 390*390*210 ( картон ящ.)Для заморозки');
INSERT INTO public."Products"(nameproduct) VALUES ('Гречка');
INSERT INTO public."Products"(nameproduct) VALUES ('Глофа');
INSERT INTO public."Products"(nameproduct) VALUES ('Гірчиця');
INSERT INTO public."Products"(nameproduct) VALUES ('Дріжді прес ефект');
INSERT INTO public."Products"(nameproduct) VALUES ('Виноград зелений');
INSERT INTO public."Products"(nameproduct) VALUES ('Драже нонпарель пасхальна');
INSERT INTO public."Products"(nameproduct) VALUES ('Желатин');
INSERT INTO public."Products"(nameproduct) VALUES ('Згущувач Жель мікс');
INSERT INTO public."Products"(nameproduct) VALUES ('Коньяк');
INSERT INTO public."Products"(nameproduct) VALUES ('Какао порошок');
INSERT INTO public."Products"(nameproduct) VALUES ('Коріандер мелений');
INSERT INTO public."Products"(nameproduct) VALUES ('Картопля свіжа');
INSERT INTO public."Products"(nameproduct) VALUES ('Кмин');
INSERT INTO public."Products"(nameproduct) VALUES ('Кокосова стружка');
INSERT INTO public."Products"(nameproduct) VALUES ('Коробка екран 285*243*65 Т-22');
INSERT INTO public."Products"(nameproduct) VALUES ('Крохмаль кукурудзяний');
INSERT INTO public."Products"(nameproduct) VALUES ('Крупа кукурудзяна');
INSERT INTO public."Products"(nameproduct) VALUES ('Кульки 14*4*45');
INSERT INTO public."Products"(nameproduct) VALUES ('Кульки 18*4*35');
INSERT INTO public."Products"(nameproduct) VALUES ('Куркума');
INSERT INTO public."Products"(nameproduct) VALUES ('Кетчуп');
INSERT INTO public."Products"(nameproduct) VALUES ('Кульки для кексів 200*300');
INSERT INTO public."Products"(nameproduct) VALUES ('Кунжут');
INSERT INTO public."Products"(nameproduct) VALUES ('Ковбаса мисливська');
INSERT INTO public."Products"(nameproduct) VALUES ('Капуста');
INSERT INTO public."Products"(nameproduct) VALUES ('Лимонна кислота');
INSERT INTO public."Products"(nameproduct) VALUES ('Лимон');
INSERT INTO public."Products"(nameproduct) VALUES ('Майонез');
INSERT INTO public."Products"(nameproduct) VALUES ('Ківі');
INSERT INTO public."Products"(nameproduct) VALUES ('Морква');
INSERT INTO public."Products"(nameproduct) VALUES ('Маргарин фрітюрний');
INSERT INTO public."Products"(nameproduct) VALUES ('Мішок для заморозки 550*1100*0,040');
INSERT INTO public."Products"(nameproduct) VALUES ('Мішок б*У');
INSERT INTO public."Products"(nameproduct) VALUES ('Начинка сирна');
INSERT INTO public."Products"(nameproduct) VALUES ('Олія рафінована');
INSERT INTO public."Products"(nameproduct) VALUES ('Оцет');
INSERT INTO public."Products"(nameproduct) VALUES ('Перець чорний мелений');
INSERT INTO public."Products"(nameproduct) VALUES ('Посипка нонпарель');
INSERT INTO public."Products"(nameproduct) VALUES ('Пластівці вівсяні');
INSERT INTO public."Products"(nameproduct) VALUES ('Поліетиленові пакети 26*6*50');
INSERT INTO public."Products"(nameproduct) VALUES ('Плівка 250 термозбіжна ПВХ 15мкм');
INSERT INTO public."Products"(nameproduct) VALUES ('Плівка 300 термозбіжна ПВХ 15мкм');
INSERT INTO public."Products"(nameproduct) VALUES ('Плівка 350 термозбіжна ПВХ 15мкм');
INSERT INTO public."Products"(nameproduct) VALUES ('Плівка стрейтч 17*500*250(конд)');
INSERT INTO public."Products"(nameproduct) VALUES ('Поліпшувач Мажемікс жовтий');
INSERT INTO public."Products"(nameproduct) VALUES ('Поліпшувач Мажемікс синій');
INSERT INTO public."Products"(nameproduct) VALUES ('Поліпшувач Пан-Фріз');
INSERT INTO public."Products"(nameproduct) VALUES ('Патока');
INSERT INTO public."Products"(nameproduct) VALUES ('Повидло з аром. Абрикосу');
INSERT INTO public."Products"(nameproduct) VALUES ('Приправа мівіна');
INSERT INTO public."Products"(nameproduct) VALUES ('Розрихлювач');
INSERT INTO public."Products"(nameproduct) VALUES ('Рис пропарений');
INSERT INTO public."Products"(nameproduct) VALUES ('Родзинки');
INSERT INTO public."Products"(nameproduct) VALUES ('Сіль кухонна');
INSERT INTO public."Products"(nameproduct) VALUES ('Сир твердий');
INSERT INTO public."Products"(nameproduct) VALUES ('Сорбінова кислота');
INSERT INTO public."Products"(nameproduct) VALUES ('Скотч (для склеювання ящиків)');
INSERT INTO public."Products"(nameproduct) VALUES ('Сода харчова');
INSERT INTO public."Products"(nameproduct) VALUES ('Солод житній порошкоподібний');
INSERT INTO public."Products"(nameproduct) VALUES ('Сир кисломолочний');
INSERT INTO public."Products"(nameproduct) VALUES ('Спирт');
INSERT INTO public."Products"(nameproduct) VALUES ('Супер декор посипка');
INSERT INTO public."Products"(nameproduct) VALUES ('Суха клейковина');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка 2224');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка 7111');
INSERT INTO public."Products"(nameproduct) VALUES ('Філе куряче');
INSERT INTO public."Products"(nameproduct) VALUES ('Форма фольгова');
INSERT INTO public."Products"(nameproduct) VALUES ('Форма для паски П3');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка пластикова 1209 к/1209д.б. 200шт.');
INSERT INTO public."Products"(nameproduct) VALUES ('Сливи');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка ПС-56');
INSERT INTO public."Products"(nameproduct) VALUES ('Стрічка кліпсуюча(хлібна - 1 уп-6шт)');
INSERT INTO public."Products"(nameproduct) VALUES ('Форма для паски л2');
INSERT INTO public."Products"(nameproduct) VALUES ('Форма куліч');
INSERT INTO public."Products"(nameproduct) VALUES ('Форма для пасок 70*85');
INSERT INTO public."Products"(nameproduct) VALUES ('Цінник малий');
INSERT INTO public."Products"(nameproduct) VALUES ('Цукати');
INSERT INTO public."Products"(nameproduct) VALUES ('Цукор білий');
INSERT INTO public."Products"(nameproduct) VALUES ('Часник');
INSERT INTO public."Products"(nameproduct) VALUES ('Ядро Соняшник');
INSERT INTO public."Products"(nameproduct) VALUES ('Яечний порошок');
INSERT INTO public."Products"(nameproduct) VALUES ('Яблука');
INSERT INTO public."Products"(nameproduct) VALUES ('Кориця');
INSERT INTO public."Products"(nameproduct) VALUES ('Блістер 2228(Рулетниця)');
INSERT INTO public."Products"(nameproduct) VALUES ('Кефір');
INSERT INTO public."Products"(nameproduct) VALUES ('Шоколад');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка 1171ковпак/1181дб(250шт)');
INSERT INTO public."Products"(nameproduct) VALUES ('Кава Галка');
INSERT INTO public."Products"(nameproduct) VALUES ('Суміш для біcквітів');
INSERT INTO public."Products"(nameproduct) VALUES ('Борошно пшеничне 1/г');
INSERT INTO public."Products"(nameproduct) VALUES ('Глазур біла №22');
INSERT INTO public."Products"(nameproduct) VALUES ('Маргарин для ш/тіста (слойка)');
INSERT INTO public."Products"(nameproduct) VALUES ('Маргарин для тортів');
INSERT INTO public."Products"(nameproduct) VALUES ('Маргарин "Столичнтй"');
INSERT INTO public."Products"(nameproduct) VALUES ('Мак голубий');
INSERT INTO public."Products"(nameproduct) VALUES ('Глазур кондитерська №7');
INSERT INTO public."Products"(nameproduct) VALUES ('Глазур шоколадна капля');
INSERT INTO public."Products"(nameproduct) VALUES ('Виноград синій');
INSERT INTO public."Products"(nameproduct) VALUES ('Молоко згущене з цукром');
INSERT INTO public."Products"(nameproduct) VALUES ('молоко сухе, знежирене');
INSERT INTO public."Products"(nameproduct) VALUES ('Мафін мікс');
INSERT INTO public."Products"(nameproduct) VALUES ('Продуктмолоковмістний сир "Київський"');
INSERT INTO public."Products"(nameproduct) VALUES ('Абрикоси консервован');
INSERT INTO public."Products"(nameproduct) VALUES (' Начинка шоколадна №5');
INSERT INTO public."Products"(nameproduct) VALUES ('кріп сушений');
INSERT INTO public."Products"(nameproduct) VALUES ('наповнювач малиновий');
INSERT INTO public."Products"(nameproduct) VALUES ('Борошно В/Г (на підпил)');
INSERT INTO public."Products"(nameproduct) VALUES ('Плівка 200 термозбіжна ПВХ 15мкм');
INSERT INTO public."Products"(nameproduct) VALUES ('начинка макова');
INSERT INTO public."Products"(nameproduct) VALUES ('кульки 14*4*35');
INSERT INTO public."Products"(nameproduct) VALUES ('Кульки п/е 350*1100*0,04');
INSERT INTO public."Products"(nameproduct) VALUES ('Шинка куряча');
INSERT INTO public."Products"(nameproduct) VALUES ('Блістер 1181');
INSERT INTO public."Products"(nameproduct) VALUES ('Блістер 1209');
INSERT INTO public."Products"(nameproduct) VALUES ('Шоколадна паста');
INSERT INTO public."Products"(nameproduct) VALUES ('Мисливська ковбаса');
INSERT INTO public."Products"(nameproduct) VALUES ('Ароматизатор лимонний');
INSERT INTO public."Products"(nameproduct) VALUES ('Молоко згущене "Іриска" варене');
INSERT INTO public."Products"(nameproduct) VALUES ('Молоко згущене варене');
INSERT INTO public."Products"(nameproduct) VALUES ('смородина свіжозаморожена');
INSERT INTO public."Products"(nameproduct) VALUES ('яблука свіжоморожені');
INSERT INTO public."Products"(nameproduct) VALUES ('Глазур чорна');
INSERT INTO public."Products"(nameproduct) VALUES ('Яйця курячі');
INSERT INTO public."Products"(nameproduct) VALUES ('Глазур шоколадна');
INSERT INTO public."Products"(nameproduct) VALUES ('Крихта бісквітна');
INSERT INTO public."Products"(nameproduct) VALUES ('Ароматизатор ванільний');
INSERT INTO public."Products"(nameproduct) VALUES ('Плівка 400 термозбіжна ПВХ 15мкм');
INSERT INTO public."Products"(nameproduct) VALUES ('Порошок до печива');
INSERT INTO public."Products"(nameproduct) VALUES ('Стірчка клейова');
INSERT INTO public."Products"(nameproduct) VALUES ('Блістер 1100/150');
INSERT INTO public."Products"(nameproduct) VALUES ('Короб картонний 390*390*21');
INSERT INTO public."Products"(nameproduct) VALUES ('Черешня цукат');
INSERT INTO public."Products"(nameproduct) VALUES ('Екстракт житній глофа');
INSERT INTO public."Products"(nameproduct) VALUES ('Покращувач Ібіс');
INSERT INTO public."Products"(nameproduct) VALUES ('Персики консервовані (460 гр- банка)');
INSERT INTO public."Products"(nameproduct) VALUES ('Сосики хот-дог');
INSERT INTO public."Products"(nameproduct) VALUES ('Дріжджі прес Екстра');
INSERT INTO public."Products"(nameproduct) VALUES ('Пергаментний папір');
INSERT INTO public."Products"(nameproduct) VALUES ('Маргарин "Максим меланж"');
INSERT INTO public."Products"(nameproduct) VALUES ('Десерт "Маскарпоне"');
INSERT INTO public."Products"(nameproduct) VALUES ('Вершки рослинні');
INSERT INTO public."Products"(nameproduct) VALUES ('Суміш для бісквітів медових');
INSERT INTO public."Products"(nameproduct) VALUES ('Запорізька слойка');
INSERT INTO public."Products"(nameproduct) VALUES ('сироватка суха молочна');
INSERT INTO public."Products"(nameproduct) VALUES ('Манка');
INSERT INTO public."Products"(nameproduct) VALUES ('Ковбаса кіпчена');
INSERT INTO public."Products"(nameproduct) VALUES ('Гриби');
INSERT INTO public."Products"(nameproduct) VALUES ('Начинка вишнева');
INSERT INTO public."Products"(nameproduct) VALUES ('Начинка яблучна');
INSERT INTO public."Products"(nameproduct) VALUES ('Начинка горохова');
INSERT INTO public."Products"(nameproduct) VALUES ('Маскарпоне');
INSERT INTO public."Products"(nameproduct) VALUES ('Начинка яблучно-вишнева');
INSERT INTO public."Products"(nameproduct) VALUES ('Олія нерафінована');
INSERT INTO public."Products"(nameproduct) VALUES ('Плівка 450 термозбіжна ПВХ 15мкм');
INSERT INTO public."Products"(nameproduct) VALUES ('Пудра термо');
INSERT INTO public."Products"(nameproduct) VALUES ('Ельдорадо кларо-гель');
INSERT INTO public."Products"(nameproduct) VALUES ('Апельсини');
INSERT INTO public."Products"(nameproduct) VALUES ('Мандарини');
INSERT INTO public."Products"(nameproduct) VALUES ('тара разова103/500 (сердечка)');
INSERT INTO public."Products"(nameproduct) VALUES ('Сироватка');
INSERT INTO public."Products"(nameproduct) VALUES ('Цибуля');
INSERT INTO public."Products"(nameproduct) VALUES ('Блістер "Сердечко"');
INSERT INTO public."Products"(nameproduct) VALUES ('Сіль вуглеамонійна (амоній)');
INSERT INTO public."Products"(nameproduct) VALUES ('Чай "Тесс" зелений');
INSERT INTO public."Products"(nameproduct) VALUES ('Капучіно стікер');
INSERT INTO public."Products"(nameproduct) VALUES ('Філе куряче кіпчене');
INSERT INTO public."Products"(nameproduct) VALUES ('Ковбаса куряча');
INSERT INTO public."Products"(nameproduct) VALUES ('Спред');
INSERT INTO public."Products"(nameproduct) VALUES ('Цедра');
INSERT INTO public."Products"(nameproduct) VALUES ('Маргарин "Пуратус" (Арісто Пастрі)');
INSERT INTO public."Products"(nameproduct) VALUES ('Поліпшувач Мажемікс салатовий');
INSERT INTO public."Products"(nameproduct) VALUES ('Петрушка сушена');
INSERT INTO public."Products"(nameproduct) VALUES ('Фарш курячий');
INSERT INTO public."Products"(nameproduct) VALUES ('Наповнювач "Вишня"');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка ПС - 56');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка УП - 80');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка УП - 80 ( 80/150)');
INSERT INTO public."Products"(nameproduct) VALUES ('Упаковка ПС - 56 (квадратні торти)');
INSERT INTO public."Products"(nameproduct) VALUES ('Посипка кольорова');
INSERT INTO public."Products"(nameproduct) VALUES ('Блістер 80/150 (квадратні торти)');
INSERT INTO public."Products"(nameproduct) VALUES ('Поліпшувач мажемікс фіолетовий');
INSERT INTO public."Products"(nameproduct) VALUES ('Кульки п/п 100х200');
INSERT INTO public."Products"(nameproduct) VALUES ('Кульки 200х350');
INSERT INTO public."Products"(nameproduct) VALUES ('Амоній');
INSERT INTO public."Products"(nameproduct) VALUES ('Ковбаса варена');
INSERT INTO public."Products"(nameproduct) VALUES ('Начинка пломбір');
INSERT INTO public."Products"(nameproduct) VALUES ('Начинка шоколад');
INSERT INTO public."Products"(nameproduct) VALUES ('Стаканчик паперовий на паску 0,1');
INSERT INTO public."Products"(nameproduct) VALUES ('Кульки пасхальні');
INSERT INTO public."Products"(nameproduct) VALUES ('Стрічка серпантинова');
INSERT INTO public."Products"(nameproduct) VALUES ('Набір "Веснянки"');
INSERT INTO public."Products"(nameproduct) VALUES ('Цукрові кульки');
INSERT INTO public."Products"(nameproduct) VALUES ('Стрічка паперова');
INSERT INTO public."Products"(nameproduct) VALUES ('Стрічка металічна');
